title = 'Afroyumbo'
baseURL = 'http://afroyumbo.com.co'
languageCode = "es-CO"
theme = "ananke"
defaultContentLanguage = "es"

linkToCover = "/images/main-banner.jpg"
[params]
[[params.ananke_socials]]
name = "facebook"
url = "https://facebook.com/"